holy moly, actions/checkout@v2 leaves secrets lying around

diff --git a/.github/workflows/cronjob.yml b/.github/workflows/cronjob.yml
--- a/.github/workflows/cronjob.yml
+++ b/.github/workflows/cronjob.yml
@@ -19,6 +19,21 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
+      - name: Cleanup secrets that actions/checkout@v2 leaves lying around.
+        run: |
+          # Cleanup adapted from actions/checkout@v2's `Post Run` action output.
+          # Ideally, I would prefer to be force the post action to run straight away,
+          # but I can't see a way to do this.
+          set -euxo pipefail
+
+          git config --local --name-only --get-regexp core\.sshCommand && git config --local --unset-all 'core.sshCommand' || :
+          git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
+
+          if git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader; then
+              git config --local --unset-all http.https://github.com/.extraheader
+          fi
+          git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
+
       - name: find crate to build
         id: find_crate
         env:
